<?php

namespace App\Enums;

enum SchoolType: int
{
	case BRANZOWA_SZKOLA_I_STOPNIA = 0;
	case BRANZOWA_SZKOLA_II_STOPNIA = 1;
	case SZKOLA_SPECJALNA_PRZYSPOSABIAJACA_DO_PRACY = 2;
	case POLICEALNA_SZKOLA_MUZYCZNA = 3;
	case POLICEALNA_SZKOLA_PLASTYCZNA = 4;
	case SZKOLA_POLICEALNA = 5;
	case LICEUM_OGOLNOKSZTALCACE = 6;
	case LICEUM_OGOLNOKSZTALCACE_UZUPELNIAJACE_DLA_ABSOLWENTOW_ZASADNICZYCH_SZKOL_ZAWODOWYCH = 8;
	case LICEUM_SZTUK_PLASTYCZNYCH = 9;
	case TECHNIKUM = 10;
	case OGOLNOKSZTALCACA_SZKOLA_BALETOWA = 11;
	case OGOLNOKSZTALCACA_SZKOLA_MUZYCZNA_I_STOPNIA = 12;
	case OGOLNOKSZTALCACA_SZKOLA_MUZYCZNA_II_STOPNIA = 13;
	case OGOLNOKSZTALCACA_SZKOLA_SZTUK_PIEKNYCH = 24;
	case SZKOLA_PODSTAWOWA = 25;
	case ZESPOL_SZKOL_I_PLACOWEK_OSWIATOWYCH = 90;
}
